---

- name: Create systemd services
  with_items: "{{ ha_storage.filesystems }}"
  template: src=postmount.service.j2 dest=/etc/systemd/system/postmount-{{ ha_storage.volume_group }}-{{ item.lv }}.service
  when:
    - item.owner is defined
    - item.group is defined

- name: Reload systemd
  command: systemctl daemon-reload
