---

- name: Dataset create "{{ ha_storage.volume_group }}/{{ item.lv }}"
  when:
    - item.lv is defined
    - item.mountpoint is defined
  shell: >
    set -o pipefail ; \
    zfs list | grep -q {{ ha_storage.volume_group }}/{{ item.lv }} || \
    zfs create "{{ ha_storage.volume_group }}/{{ item.lv }}" \
    {% if item.size is defined %}
        -o quota={{ item.size }} \
    {% endif %}
        -o mountpoint="{{ ha_storage_zpool_mountpoint }}/{{ item.mountpoint }}"
