---

- name: Install clvm packages
  package:
    name: "{{ ha_storage_clvm_packages }}"
    state: "{{ ha_storage_package_state }}"
    update_cache: "{{ ansible_pkg_mgr == 'apt' | ternary('yes', omit) }}"
    cache_valid_time: "{{ ansible_pkg_mgr == 'apt' | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  tags:
    - install-apt
    - install-yum
    - instal-zypper

- name: Install ocfs2 packages
  package:
    name: "{{ ha_storage_ocfs2_packages }}"
    state: "{{ ha_storage_package_state }}"
    update_cache: "{{ ansible_pkg_mgr == 'apt' | ternary('yes', omit) }}"
    cache_valid_time: "{{ ansible_pkg_mgr == 'apt' | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  tags:
    - install-apt
    - install-yum
    - instal-zypper
#  when: '"ocfs2" in ha_storage.filesystems|json_query("fstype")'
  when: '"ocfs2" in ha_storage.filesystems'

- name: Install some crm scripts (directories)
  file: path={{ ha_storage_crm_scripts_root_path }}/{{ item }} state=directory
  with_items: "{{ ha_storage_crm_scripts }}"

- name: Install some crm scripts (files)
  copy: src=scripts/{{ item }}.yml dest={{ ha_storage_crm_scripts_root_path }}/{{ item }}/main.yml
  with_items: "{{ ha_storage_crm_scripts }}"
