---

- name: Locate the volume group resource "g-{{ ha_storage.volume_group }}"
  shell: >
    crm_resource --locate --resource "g-{{ ha_storage.volume_group }}" \
        | awk '{print $NF}'
  register: crm_resource_locate_group
  run_once: true

- name: LV create "{{ ha_storage.volume_group }}/{{ item.lv }}"
  lvol: vg={{ ha_storage.volume_group }} lv={{ item.lv }} size={{ item.size }} opts="-m{{ lvm_mirors }}"
  when:
    - item.fstype != "tmpfs"
    - crm_resource_locate_group.stdout.find(ansible_hostname) > -1

- name: Cleanup the resource group
  shell: pcs resource cleanup g-{{ ha_storage.volume_group }}
  when: crm_resource_locate_group.stdout.find("NOT") > -1

- name: LV mkfs "{{ ha_storage.volume_group }}/{{ item.lv }}"
  filesystem: fstype={{ item.fstype | default(ha_storage_fs) }} dev=/dev/{{ ha_storage.volume_group }}/{{ item.lv }}
  when:
    - item.fstype != "tmpfs"
    - crm_resource_locate_group.stdout.find(ansible_hostname) > -1

- name: Check group configuration "{{ ha_storage.volume_group }}_rg"
  shell: pcs resource show g-{{ ha_storage.volume_group }} | fgrep Resource
  register: pcs_group_conf

- name: Create primitive "{{ ha_storage.volume_group }}_{{ item.lv }}"
  shell: >
    pcs resource create "{{ ha_storage.volume_group }}_{{ item.lv }}" Filesystem \
        directory="{{ item.mountpoint }}" \
        device="/dev/{{ ha_storage.volume_group }}/{{ item.lv }}" \
        fstype="{{ item.fstype }}" \
        op monitor timeout=40 interval=20 \
        op start timeout=60 interval=0 \
        op stop timeout=60 interval=0 \
        --group g-{{ ha_storage.volume_group }}
  when:
    - pcs_group_conf.stdout.find(item.lv) < 0

- name: Check "{{ ha_storage.volume_group }}_vg"
  shell: crm_resource --locate --resource "{{ ha_storage.volume_group }}_vg"
  register: crm_resource_locate_vg
  run_once: true

- name: Cleanup "{{ ha_storage.volume_group }}_vg"
  shell: pcs resource cleanup {{ ha_storage.volume_group }}_vg
  when: crm_resource_locate_vg.stdout.find('NOT') > -1
  run_once: true
